# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Faq"
client_id = "b2fef71648e22a22718782b92a48ff96"
application_url = "https://b0c9-119-82-70-201.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://b0c9-119-82-70-201.ngrok-free.app/authenticate" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
